(defpackage :om (:use :common-lisp))

(load "tools.lisp")
(load "lisptools.lisp")
(load "lists.lisp")
(load "midi.lisp")
;;;(load "genfunmetaclass.lisp")

;;;(load "basicboxes.lisp")
;;;(load "metaclasses.lisp")
;;;(load "maquettecontainer.lisp")
;;;(load "system.lisp")

;;;(load "etf.lisp")
;;;(load "scoreobject.lisp")
;;;(load "chordseq.lisp")
(load "midi-api.lisp")
(load "midifile.lisp")
(load "kernel.lisp")
(load "lz.lisp")